config/routes.rb
Rails.application.routes.draw do
  # devise_for :views
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get '/orders/home', to: 'orders#home', as: 'home_orders'
  get '/orders/:id/sms', to: 'orders#sms', as: 'sms_order'
  post '/orders/call', to: 'orders#call', as: 'call_order'
  resources :orders
  get '/users/:id', to: 'users#show', as: 'user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'orders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
require 'twilio-ruby'
# require 'dotenv/load'

class OrdersController < ApplicationController
  # skip_before_action :verify_authenticity_token, only: [:call]
  protect_from_forgery except: :call
  before_action :set_order, only: [:show, :edit, :update, :destroy, :sms]
  before_action :authenticate_user!, except: [:home, :index, :call]

  # GET /orders
  # GET /orders.json
  def index
    if user_signed_in?
      @orders = Order.where(user_id: current_user)
    elsif params[:store]
      if User.find_by id: params[:store]
        @user = User.find(params[:store])
        @orders = Order.where(user_id: @user.id)
      else
        render "home"
        flash[:notice] = "Store ID does not exist"
      end
    else
      redirect_to home_orders_path
    end
    # render json: @orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end

    account_sid = ENV['TWILIO_ACCOUNT_SID']
    auth_token = ENV['TWILIO_AUTH_TOKEN']
    client = Twilio::REST::Client.new(account_sid, auth_token)

    sender = '+19802701816' # Your Twilio number
    receiver = '+65' + @order.number # Your mobile phone number
  
    client.messages.create(
      from: sender,
      to: receiver,
      body: "Hi " + @order.name + ", you have placed an order with " + current_user.company_name + "!"
    )
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sms
    redirect_to orders_path
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    auth_token = ENV['TWILIO_AUTH_TOKEN']
    client = Twilio::REST::Client.new(account_sid, auth_token)

    sender = '+19802701816' # Your Twilio number
    receiver = '+65' + @order.number # Your mobile phone number
  
    client.messages.create(
      from: sender,
      to: receiver,
      body: "Hi " + @order.name + ", your order is ready! See ya shortly!"
    )
  end

  def home 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :number, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :company_name)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :company_name)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
require 'rqrcode'

class UsersController < ApplicationController
  before_action :find_user

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_user
      @user = current_user
      @qr = RQRCode::QRCode.new( 'qvoca.herokuapp.com/orders?store=' + current_user.id.to_s, :size => 4, :level => :h )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%#= favicon_link_tag 'icon.png' %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application", media: "all" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-danger navbar-dark">
      <a class="navbar-brand" href="#">V O C A</a>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "ORDERS", orders_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'PROFILE', user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "SIGN IN", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "SIGN UP", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </nav>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :number %>
    <%= form.text_field :number, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="actions form-group" align="center">
    <%= form.submit "Create", class: "btn btn-danger btn-lg" %>
  </div>
<% end %>

app/views/orders/_patron.html.erb
<div class="container-fluid">

<table class="table table-danger table-hover">
  <thead>
    <tr class="d-flex">
      <th class="col-1">S/No.</th>
      <th class="col-5">Order</th>
      <th class="col-3">Customer</th>
      <th class="col-3">Time Passed</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each_with_index { |order, index| %>
      <tr class="d-flex">
        <td class="col-1"><%= index + 1 %></td>
        <td class="col-5"><%= order.description %></td>
        <td class="col-3"><%= order.name %></td>
        <td class="col-3"><%= time_ago_in_words(order.created_at) %> ago</td>
      </tr>
    <% } %>
  </tbody>
</table>

</div>
<br/>
<div align=center>
  <%= link_to "Back", home_orders_path, class: "btn btn-danger btn-lg" %>
</div>

app/views/orders/_store.html.erb
<%= form_tag(orders_path, method: "get") do %>
  <div class="field form-group">
    <%= label_tag "store", "Enter Store ID" %>
    <%= text_field_tag "store", nil, class: "form-control", required: true %>
  </div>

  <br/>
  <br/>

  <div class="actions form-group" align="center">
    <%= submit_tag "Go", class: "btn btn-outline-light text-light btn-lg" %>
  </div>

<% end %>

app/views/orders/_vendor.html.erb
<table class="table table-danger table-hover">
  <thead>
    <tr class="d-flex">
      <th class="col-1">S/No.</th>
      <th class="col-4">Order</th>
      <th class="col-2">Customer</th>
      <th class="col-2">Time Passed</th>
      <th class="col-1"></th>
      <th class="col-1"></th>
      <th class="col-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each_with_index { |order, index| %>
      <tr class="d-flex">
        <td class="col-1"><%= index + 1 %></td>
        <td class="col-4"><%= order.description %></td>
        <td class="col-2"><%= order.name %></td>
        <td class="col-2"><%= time_ago_in_words(order.created_at) %> ago</td>
        <td class="col-1"><%= link_to 'Edit', edit_order_path(order), class: "btn btn-dark btn-block" %></td>
        <td class="col-1"><%= link_to 'Done', order, method: :delete, data: { confirm: 'Food collected?' }, class: "btn btn-dark btn-block" %></td>
        <td class="col-1"><%= link_to 'SMS', sms_order_path(order), class: "btn btn-dark btn-block" %></td>
      </tr>
    <% } %>
  </tbody>
</table>
<div align="center">
  <%= link_to 'Add Order', new_order_path, class: "btn btn-danger btn-lg" %>
</div>

app/views/orders/edit.html.erb
<div class="container">
	<h1 class="text-center">Editing Order</h1>
	<%= render 'form', order: @order %>
</div>

app/views/orders/home.html.erb
<div class="container">
	<h1 class="text-center">Welcome to VOCA!</h1>
	<br/>
	<br/>
	<p class="text-center">Go to the store's page to check the order queue and where your order is in line:-</p>
	<br/>
	<%= render 'store' %>
	<% if user_signed_in? %>
		<%= link_to 'Orders', orders_path %>
	<% end %>
</div>
<br/>

app/views/orders/index.html.erb
<div class="container">
  <h1 class="text-center">
    <% if params[:store] %>
      <%= @user.company_name %>
    <% else %>
      <%= current_user.company_name %>
    <% end %>
  </h1>
  <br/>
  <% if user_signed_in? %>
    <%= render 'vendor' %>
  <% else %>
    <%= render 'patron' %>
  <% end %>
  <br>
  
</div>

app/views/orders/new.html.erb
<div class="container">
	<h1 class="text-center">New Order</h1>
	<br/>
	<%= render 'form', order: @order %>
</div>

app/views/orders/show.html.erb
<div class="container">
	<h1 class="text-center"><%= @order.description %></h1>
	<br/>
	<br/>
	<div align="center">
		<%= link_to 'Edit', edit_order_path(@order), class: "btn btn-danger btn-lg" %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container text-center">
	<h2><%= @user.company_name %></h2>
	<br/>
	<div class="qr" align="center">
		<%= raw @qr.as_html %>
	</div>
</div>